# Site settings
title:          Amass, bridge and combine
description:    ""
baseurl:        "/blogtest/"
url:            "https://sunnyoaks.github.io/blogtest/"

# Author
author:
  name:         Baptiste Marescaux
  email:        baptiste@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
